local_backend: true

logo_url: /logo.svg

backend:
    name: github
    branch: main
    repo: zankhq/astro-starter
    site_domain: astrostarter.majestico.it
    base_url: https://astrostarter.majestico.it
    auth_endpoint: oauth
    automatic_deployments: true

media_folder: "src/assets/images"
public_folder: "@assets/images"

i18n:
    structure: "multiple_folders"
    locales:
        - "en"
        - "it"
    default_locale: "en"

collections:
    - name: "products"
      label: "Productes (Catalog)"
      folder: "src/content/products"
      create: true
      delete: true
      fields:
          - { label: "Nom del Producte", name: "title", widget: "string" }
          - { label: "Preu (€)", name: "price", widget: "number", value_type: "float" }
          - { label: "Imatge Frontal", name: "imageFront", widget: "image" }
          - { label: "Imatge Detall / Backprint", name: "imageBack", widget: "image" }
          - { label: "Estat (Sold Out / Agotat)", name: "isSoldOut", widget: "boolean", default: false }
          - { label: "Badge / Etiqueta", name: "badge", widget: "string", required: false }
          - { label: "Talles Disponibles", name: "sizes", widget: "list", default: ["S", "M", "L", "XL"] }
          - { label: "Descripció", name: "body", widget: "markdown", required: false }

    - name: "posts"
      i18n: true
      label: "Blog Posts / Notícies"
      folder: "src/content/blog"
      media_folder: "/src/assets/images/blog"
      public_folder: "@assets/images/blog"
      create: true
      delete: true
      fields:
          - name: "title"
            widget: "string"
            label: "Post Title"
            i18n: true
          - label: "Description"
            name: "description"
            widget: "string"
            i18n: true
          - label: "Publish Date"
            name: "pubDate"
            widget: "datetime"
            format: "YYYY-MM-DD HH:mm"
            i18n: "duplicate"
          - label: "Image"
            name: "heroImage"
            widget: "image"
            i18n: "duplicate"
          - name: "body"
            widget: "markdown"
            label: "Post Body"
            i18n: true
